<a href="https://colab.research.google.com/github/magdamadej/NumPy/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
Podstawy biblioteki numpy

## Instalacja
Aby zainstalować bibliotekę NumPy należy użyć polecenia:
`pip install numpy`

## Podstawy

In [44]:
import numpy as np
np.__version__

'2.0.2'

### 1D Array

In [5]:
x = np.array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
#rozmiar
x.ndim

1

In [9]:
#kształt
x.shape

(2,)

In [11]:
#liczba elementów
x.size

2

In [12]:
x.dtype

dtype('int64')

In [17]:
x = np.array([1.3, 2.3, 1.4])

In [15]:
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

In [19]:
x.shape

(3,)

### 2D Array

In [25]:
x = np.array([[1, 2, 3], [-3, 1, 2]])
x

array([[ 1,  2,  3],
       [-3,  1,  2]])

In [26]:
x.ndim

2

In [28]:
# pierwsza wartość (2) - 2 wiersze, czyli 2 zagnieżdżone listy
# druga wartość (3) - 3 kolumny, czyli 3 elementy w każdej zagnieżdżonej liście
x.shape

(2, 3)

In [30]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [31]:
x.shape

(2, 3)

In [32]:
x.size

6

### 3D Array

In [33]:
x = np.array(
     [[[4,3,2],
       [3, 1, 2]],

      [[3, 2, 1],
       [4, 2, 1]]]
 )
x

array([[[4, 3, 2],
        [3, 1, 2]],

       [[3, 2, 1],
        [4, 2, 1]]])

In [34]:
x.ndim

3

In [36]:
x.shape
# pierwsze 2 - 2 dwie tablice
# drugie 2 - 2 wiersze
# 3 - 3 kolumny

(2, 2, 3)

In [37]:
x.size

12

### Typy danych

In [38]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [39]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [3]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [4]:
A = np.array([1, 2.7, 3.3], dtype='int')
A

array([1, 2, 3])

In [10]:
A = np.array([24, 100, 120], dtype=np.int8)

In [12]:
A

array([ 24, 100, 120], dtype=int8)

### Tworzenie tablic

In [13]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [18]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [20]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
A = np.arange(15)

In [23]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje na tablicach

In [29]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [31]:
# dodawanie - taka sama ilość elementów
A + B

array([6, 0, 7, 4])

In [32]:
# odejmowanie
A - B

array([0, 2, 1, 0])

In [33]:
A * B

array([ 9, -1, 12,  4])

In [34]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [35]:
A + 3

array([6, 4, 7, 5])

In [36]:
2 * A

array([6, 2, 8, 4])

In [37]:
A + 3*B

array([12, -2, 13,  8])

In [38]:
np.add(A, B)

array([6, 0, 7, 4])

In [39]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [40]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [42]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [43]:
# mnożenie macierzy
np.dot(X, Y)
# lub X.dot(Y)
# lub X @ Y

array([[  3,   6],
       [-12,   0]])

### Generowanie liczb pseudolosowych

In [45]:
np.random.seed(0)

In [46]:
np.random.randn()

1.764052345967664

In [47]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [49]:
np.random.randn(10, 4)

array([[ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
       [ 0.12898291,  1.13940068, -1.23482582,  0.40234164],
       [-0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244],
       [-1.53624369,  1.48825219,  1.89588918,  1.17877957],
       [-0.17992484, -1.07075262,  1.05445173, -0.40317695]])

### Podstawowe funkcje w bibliotece NumPy

In [51]:
np.sqrt(9)

np.float64(3.0)

In [53]:
np.all([3, 2, 1])

np.True_

In [54]:
np.any([0, 0, 0])

np.False_

In [55]:
A = np.array([10, 20, 30, 40, 50])

In [56]:
np.argmax(A)

np.int64(4)

In [57]:
np.argmin(A)

np.int64(0)

In [58]:
np.max(A)

np.int64(50)

In [59]:
np.min(A)

np.int64(10)

In [60]:
np.mean(A)

np.float64(30.0)

In [61]:
np.median(A)

np.float64(30.0)

In [62]:
np.std(A)

np.float64(14.142135623730951)

### Indeksowanie i wycinanie tablic

In [63]:
A = np.arange(20)

In [64]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [65]:
# A[start:stop], A[index], A[:stop] A[start:]
A[2]

np.int64(2)

In [66]:
A[:5]

array([0, 1, 2, 3, 4])

In [73]:
A = A.reshape((4, -1))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
A[0]

array([0, 1, 2, 3, 4])

In [75]:
A[:,0]

array([ 0,  5, 10, 15])

In [76]:
A[1, 2]

np.int64(7)

In [78]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

### Iteracja po tablicach

In [79]:
# iteracja po wierszach
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [80]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [81]:
# iteracja po każdym elemencie
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Zmiana rozmiaru

In [82]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [84]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Maski logiczna

In [86]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [87]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])